name: CI
on:
  push:
  pull_request:
    # any pull request

permissions:
  contents: read

env:
  FORCE_COLOR: '1'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 16.x
          - node-version: 18.x
          - node-version: 20.x
          - node-version: 22.x
    steps:
      - name: Checkout (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Checkout (Push)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0 # needed for dirty check
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Set npm version
        run: |
          corepack enable
          npm --version
      - name: Install Dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # v1.10.2
        with:
          useRollingCache: true
          install-command: npm ci --foreground-scripts
      - name: Test
        run: |
          npm run test


  compatibility-test-windows:
    name: Test Windows compatibility
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 16.x
          - node-version: 18.x
          - node-version: 20.x
          - node-version: 22.x
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Set npm version
        run: |
          corepack enable
          npm --version
      - name: Install Dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # v1.10.2
        with:
          useRollingCache: true
          install-command: npm ci --foreground-scripts
      - name: Test
        run: |
          npm run test
